# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : dandanDQ
      USER_EMAIL  : shendanqiong@qq.com
      PUBLISH_DIR : ./dist

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - run: set -e
      - run: rm -rf dist
      - run: yarn install
      - run: yarn build
      - run: cd ./dist
      - run: git init
      - run: 'git config --global user.email "shendanqiong@qq.com"'
      - run: 'git config --global user.name "dandanDQ"'
      - run: git add .
      - run: "git commit -m 'feat: deploy'"
      - run: "git push -f git@github.com:dandanDQ/resume.git master:deploy"













